fetch-sources: Allow to specify required version using regex mask

diff --git a/scripts/fetch-sources b/scripts/fetch-sources
--- a/scripts/fetch-sources
+++ b/scripts/fetch-sources
@@ -8,31 +8,40 @@ else
 	exec bash "$0" "$@"
 fi
 
+readonly DEFAULT_VER_REGEX='([0-9]+\.)+[0-9]+'
+
 case "$(uname -s)" in
 	Darwin) filesize() { stat -f %z "$@"; };;
 	*) filesize() { stat -c %s "$@"; };;
 esac
 
+version_mask_to_regex() {
+	echo "$1" | sed 's/\./\\./g;s/x/[0-9]+/g'
+}
+
 scrape_latest_version() {
 	local url=$1
-	local pattern="s/.*$2.*/\1/p"
+	local ver_regex=$2
+	local pattern="s/.*$ver_regex.*/\1/p"
 	local name=$3
 	local ver
 
 	if ver=$(curl -fsS --retry 3 "$url" | sed -En "$pattern" | sort -ruV | head -1) && [ "$ver" ]; then
 		echo "$ver"
 	else
-		echo "ERROR: Failed to find $name latest version" >&2
+		echo "ERROR: Failed to find $name version matching /$ver_regex/" >&2
 		return 1
 	fi
 }
 
 github_latest_version_tag() {
-	local repo_slug="$1"
+	local repo_slug=$1
+	local ver_regex=${2:-$DEFAULT_VER_REGEX}
 	local tags_url="https://api.github.com/repos/$repo_slug/tags"
 	local tag
 
-	local jq_filter_tags='. | map(.name | select(test("^v?\\d+(\\.\\d+)+$")))'
+	local ver_regex_esc=$(printf '%s\n' "$ver_regex" | sed 's/\\/\\\\/g')
+	local jq_filter_tags=". | map(.name | select(test(\"^v?$ver_regex_esc$\")))"
 	local jq_latest='max_by(sub("^v"; "") | split(".") | map(tonumber))'
 
 	# XXX: Hack for https://github.com/openresty/headers-more-nginx-module/issues/117.
@@ -43,7 +52,7 @@ github_latest_version_tag() {
 	if tag=$(github_curl "$tags_url" | jq -er "$jq_filter_tags | $jq_latest") && [ "$tag" ]; then
 		echo "$tag"
 	else
-		echo "ERROR: Failed to find $repo_slug latest version tag" >&2
+		echo "ERROR: Failed to find $repo_slug version tag matching /v?$ver_regex/" >&2
 		return 1
 	fi
 }
@@ -68,29 +77,38 @@ checksum() {
 
 
 if [ $# -lt 1 ] || [ "$1" = '--help' ]; then
-	echo "Usage: $0 <proj-name> [<proj-name>...]" >&2
+	echo "Usage: $0 <proj-name>[@<version-mask>] [<proj-name>[@<version-mask>]...]" >&2
 	exit 2
 fi
 
-for name in "$@"; do
+
+for item in "$@"; do
+	name=${item%@*}
+
+	if [ "$name" = "${item#*@}" ]; then
+		ver_regex=''
+	else
+		ver_regex=$(version_mask_to_regex "${item#*@}")
+	fi
+
 	case "$name" in
 		openssl)
 			base_url='https://www.openssl.org/source'
-			ver=$(scrape_latest_version "$base_url/" 'openssl-(1(\.[0-9]+)+[a-z]+)\.' 'openssl')
+			ver=$(scrape_latest_version "$base_url/" "openssl-(${ver_regex:-"1(\.[0-9]+)+[a-z]+"})\." 'openssl')
 			url="$base_url/$name-$ver.tar.gz"
 		;;
 		pcre)
 			base_url='https://ftp.pcre.org/pub/pcre'
-			ver=$(scrape_latest_version "$base_url/" 'pcre-(([0-9]+\.)+[0-9]+)\.' 'pcre')
+			ver=$(scrape_latest_version "$base_url/" "pcre-(${ver_regex:-$DEFAULT_VER_REGEX})\." 'pcre')
 			url="$base_url/$name-$ver.tar.bz2"
 		;;
 		zlib)
 			base_url='https://zlib.net'
-			ver=$(scrape_latest_version "$base_url/" 'zlib-(([0-9]+\.)+[0-9]+)\.' 'zlib')
+			ver=$(scrape_latest_version "$base_url/" "zlib-(${ver_regex:-$DEFAULT_VER_REGEX})\." 'zlib')
 			url="$base_url/$name-$ver.tar.xz"
 		;;
 		*)
-			tag=$(github_latest_version_tag "$name")
+			tag=$(github_latest_version_tag "$name" "$ver_regex")
 			ver=${tag#v}
 			url="https://github.com/$name/archive/$tag/${name#*/}-$ver.tar.gz"
 		;;
