fetch-sources: Improve script and remove default versions

diff --git a/scripts/fetch-sources b/scripts/fetch-sources
--- a/scripts/fetch-sources
+++ b/scripts/fetch-sources
@@ -1,18 +1,18 @@
 #!/bin/sh
 set -eu
 
-find_latest_version() {
+scrape_latest_version() {
 	local url=$1
-	local pattern=$2
-	local default=$3
+	local pattern="s/.*$2.*/\1/p"
+	local name=$3
+	local ver
 
-	local ver=$(curl -s "$url" | grep -ioP "$pattern" | sort -ruV | head -1)
-	if [ "$ver" ]; then
-		echo "Found $ver" >&2
+	if ver=$(curl -sS "$url" | sed -En "$pattern" | sort -ruV | head -1) && [ "$ver" ]; then
+		echo "Found $name latest version: $ver" >&2
 		echo "$ver"
 	else
-		echo "Failed to find latest version, using default: $default" >&2
-		echo "$default"
+		echo "ERROR: Failed to find $name latest version" >&2
+		return 1
 	fi
 }
 
@@ -20,9 +20,12 @@ upcase() {
 	echo "$1" | tr '[a-z]' '[A-Z]'
 }
 
-fetch() {
-	local name=$(basename "$1")
-	wget -c -nv "$1"
+download_tar() {
+	local url="$1"
+	local name=$(basename "$url")
+
+	echo "Downloading $url" >&2
+	wget -c -nv "$url"
 	tar -xf "$name"
 	echo "$(upcase "$NAME")_DIR=${name%.tar.*}"
 }
@@ -38,18 +41,18 @@ NAME="$1"
 case "$NAME" in
 	openssl)
 		url='https://www.openssl.org/source'
-		name=$(find_latest_version "$url/" 'openssl-1\.(\d+\.)+[a-z\d]+' 'openssl-1.1.1i')
-		fetch "$url/$name.tar.gz"
+		ver=$(scrape_latest_version "$url/" 'openssl-(1(\.[0-9]+)+[a-z]+)\.' 'openssl')
+		download_tar "$url/$NAME-$ver.tar.gz"
 	;;
 	pcre)
 		url='https://ftp.pcre.org/pub/pcre'
-		name=$(find_latest_version "$url/" 'pcre-(\d+\.)+\d+' 'pcre-8.44')
-		fetch "$url/$name.tar.bz2"
+		ver=$(scrape_latest_version "$url/" 'pcre-(([0-9]+\.)+[0-9]+)\.' 'pcre')
+		download_tar "$url/$NAME-$ver.tar.bz2"
 	;;
 	zlib)
 		url='https://zlib.net'
-		name=$(find_latest_version "$url/" 'zlib-(\d+\.)+\d+' 'zlib-1.2.11')
-		fetch "$url/$name.tar.xz"
+		ver=$(scrape_latest_version "$url/" 'zlib-(([0-9]+\.)+[0-9]+)\.' 'zlib')
+		download_tar "$url/$NAME-$ver.tar.xz"
 	;;
 	*)
 		echo "Unknown name: $1" >&2
